### ISSUE TITLE
Memory not being released[Possible Memory leack]

### ISSUE THREAD

**Issue by Albinzr** [austinh115/lz-string-go#4]
While decompression of message keeps taking memory and not releasing.

**Comment by goriyasno** [comment]
> While decompression of message keeps taking memory and not releasing.

Go is garbage collected language.

**Comment by gtsigner** [comment]
https://github.com/austinh115/lz-string-go/issues/5#issuecomment-819946979

**Comment by lazarus** [comment]
Improvements by @godtoy in #6
