### ISSUE TITLE
Performance of string + string in func DecompressFromBase64 is too bad, and strings.Builder{} or bytes.Buffer{} is better.

### ISSUE THREAD

**Issue by llj1990** [austinh115/lz-string-go#5]

**Comment by gtsigner** [comment]
i think here are some big problems with performance,it will cause performance problems when using long strings
![image](https://user-images.githubusercontent.com/13638996/114799281-ccacfe80-9d86-11eb-8441-dc41e3fedc74.png)
![image](https://user-images.githubusercontent.com/13638996/114799322-e8b0a000-9d86-11eb-9957-deb09e3920e5.png)

**Comment by Albinzr** [comment]
Is there a fix or was it just closed?

**Comment by lazarus** [comment]
> Is there a fix or was it just closed?

Fixed in #6
